steps:
  - label: Example Test
    command: echo "Hello!"

#  - wait
#
#  - label: Composer Update
#    command: composer update
#
#  - wait
#
#  - label: PHP Unit Tests
#    command: php vendor/bin/phpunit